### PR TITLE
Wordpressfix

### PR DESCRIPTION
**Pull request by astridx**
Up to now only Wordpress plugins which are in a separate folder will bee detected. 
Simple plugins in a file in the directory .../wordpress/wp-content/plugins/ - like Hello Dolly - are ignored.

This PR expands the search directories so, that files in the  folder .../wordpress/wp-content/plugins/ are searched too.

### CODE REVIEW

**Comment by SniperSister** [comment]
@astridx can you add a unit test case for this this new feature too? That would be great! :)

**Comment by astridx** [comment]
I added the unit test. If this PR will be merged the issue
https://github.com/CMS-Garden/cmsscanner/issues/15
can bee closed, too.

**Comment by zero-24** [comment]
@astridx do we need the complete code of the plugin? As for the other tests we just include the files we need.

**Comment by astridx** [comment]
@zero-24 Yes you are right. I deleted the unnecessary files.

**Comment by zero-24** [comment]
@astridx 👍 i have also added the type `plugin` as wp just know plugins we can hard code it.

Can you confirm @nullbytes ? If the tests passes now i think we are good to go 😄 👍

**Comment by SniperSister** [comment]
Looks good from my side, waiting for feedback from @nullbytes before merging

**Comment by SniperSister** [comment]
@astridx I have merged this PR now, thanks again! :)

**Pull request merged**
