### PR TITLE
Update Contao 4 support

### LINKED ISSUE #10: Add support for Contao 4 core and extensions

### PR DESCRIPTION
**Pull request by aschempp**
fixes #10

### CODE REVIEW

**Comment by vitaminless** [comment]
Thanks for the hint, I corrected it in the branch feature/whd-hackaton, I also removed the null hint cause it is simply incorrect.

**Comment by SniperSister** [comment]
AWESOME! Thank you @aschempp :)

@tobiasbaehr @vitaminless will you guys take care of merging the PR into your branch? Or should I do this?

**Comment by tobiasbaehr** [comment]
The pull request needs a reroll. But I can do it manually.

**Comment by SniperSister** [comment]
Great, thanks! Just wanted to make sure that it's clear who's going to take care of this

**Pull request closed without merging**
