### PR TITLE
fixed one failing contao test, deletet one method because the test compared o…

### PR DESCRIPTION
**Pull request by astridx**
…nly two mock objects.

### CODE REVIEW

**Comment by aschempp** [comment]
Wouldnt it be better to add the necessary fixtures so the runs sucessfully?

**Comment by aschempp** [comment]
Thanks! Could you fix the whitespaces as well?

**Comment by astridx** [comment]
@aschempp 
I inserted the method again. 
I only saw, that you compare mock json data in the file /tests/mockfiles/contao/contao3/composer/vendor/composer/installed.json with a mock array in the test method. 
What productive Contao code do you test with the test method testContao3Modules()?

**Comment by aschempp** [comment]
Unfortunately there is no production data (for none of the scanners as far as I know). The directory structures are set up like a real installation and then the scanner is tested to find what's in the files (e.g. Version numbers).

**Comment by astridx** [comment]
@aschempp Thank you for your answer.
Now I saw, that the travis check failed. But in my installation all test are green?

**Comment by aschempp** [comment]
Please look at the travis log. It says your coding style is still wrong. We're using spaces not tabs as far as I know.

**Comment by astridx** [comment]
There are not only coding standard errors. The mock date changed because of https://github.com/CMS-Garden/cmsscanner/commit/640f5439ff8e7930ea8a868cbbae207e48ca26ba
No the test are succesful

**Pull request closed without merging**
