### PR TITLE
Pivotx detection

### PR DESCRIPTION
**Pull request by helmo**
ref: http://pivotx.net/

### CODE REVIEW

**Comment by SniperSister** [comment]
Hi, thanks for your contribution, that's very much appreciated!

Could you please have a look at the feature/whd-hackathon branch? This one implements support for extension detection and I would love to see support for this in your CMS adapter too.

**Comment by helmo** [comment]
Thanks for the hint ... but I'm not a pivotx developer. I'm trying to make a list of outdated code used by clients.

And since the maintainers have indicated that [pivotx-development-has-ended](http://blog.pivotx.net/2017-03-22/pivotx-development-has-ended) ...

**Comment by SniperSister** [comment]
Ah ok, got your point. I'm willing to merge your PR but before I'll need to add some logic to output something like "module detection not supported" for systems like pivotx where the support for this feature is missing. I'll keep you in the loop, ok?

**Comment by helmo** [comment]
sure, thanks.

I also have a feature/concrete5 branch which is fairly ready ... but
I'll rebase that when your done ;)

**Comment by SniperSister** [comment]
You can't imagine how ashamed I feel that it took so long to get such a simple PR merged, but now it's finally done and merged in the dev branch.

Thanks again for you contribution, it's very appreciated!

**Pull request closed without merging**
