### PR TITLE
Remove unknown if there is nothing unknown

### PR DESCRIPTION
**Pull request by zero-24**
### New result

```
Successfully finished scan!
CMSScanner found 9 CMS installations!

+-----------+-----------------+
| CMS       | # Installations |
+-----------+-----------------+
| Joomla    | 6               |
| Drupal    | 1               |
| TYPO3 CMS | 1               |
| WordPress | 1               |
+-----------+-----------------+

Version specific stats:
Joomla:
+---------+-----------------+
| Version | # Installations |
+---------+-----------------+
| Unknown | 4               |
| 1.5.26  | 1               |
| 2.5.27  | 1               |
+---------+-----------------+
Drupal:
+---------+-----------------+
| Version | # Installations |
+---------+-----------------+
| 8.2.7   | 1               |
+---------+-----------------+
TYPO3 CMS:
+---------+-----------------+
| Version | # Installations |
+---------+-----------------+
| 7.6.15  | 1               |
+---------+-----------------+
WordPress:
+---------+-----------------+
| Version | # Installations |
+---------+-----------------+
| 4.7.3   | 1               |
+---------+-----------------+

Execution time: 1.1708610057831 seconds
Memory consumption: 4M

```

### Actual result
```
Successfully finished scan!
CMSScanner found 9 CMS installations!

+-----------+-----------------+
| CMS       | # Installations |
+-----------+-----------------+
| Joomla    | 6               |
| Drupal    | 1               |
| TYPO3 CMS | 1               |
| WordPress | 1               |
+-----------+-----------------+

Version specific stats:
Joomla:
+---------+-----------------+
| Version | # Installations |
+---------+-----------------+
| Unknown | 4               |
| 1.5.26  | 1               |
| 2.5.27  | 1               |
+---------+-----------------+
Drupal:
+---------+-----------------+
| Version | # Installations |
+---------+-----------------+
| Unknown | 0               |
| 8.2.7   | 1               |
+---------+-----------------+
TYPO3 CMS:
+---------+-----------------+
| Version | # Installations |
+---------+-----------------+
| Unknown | 0               |
| 7.6.15  | 1               |
+---------+-----------------+
WordPress:
+---------+-----------------+
| Version | # Installations |
+---------+-----------------+
| Unknown | 0               |
| 4.7.3   | 1               |
+---------+-----------------+

Execution time: 1.2243068218231 seconds
Memory consumption: 4M

```

Thanks for the idea @nullbytes

### CODE REVIEW

**Comment by SniperSister** [comment]
Hm, I think not adding the "empty" (zero) value is the better solution:
https://github.com/CMS-Garden/cmsscanner/blob/develop/src/Command/DetectCommand.php#L168

What do you think?

**Comment by zero-24** [comment]
hmm dont we need to do this as we use it here: https://github.com/CMS-Garden/cmsscanner/blob/develop/src/Command/DetectCommand.php#L177 ?

**Comment by SniperSister** [comment]
Sure, but that's we only need a simple "if it not exists yet, add it"-statement

**Comment by zero-24** [comment]
Ah ok got it. something like this https://github.com/CMS-Garden/cmsscanner/pull/38/commits/11e773898cd58f1b5449f2946ad344d0547d6459 ?

**Comment by SniperSister** [comment]
Great, one last thing: can you update the readme file to show the new output?

**Comment by zero-24** [comment]
new output example: 

```
Successfully finished scan!
CMSScanner found 5 CMS installations!

+--------+-----------------+
| CMS    | # Installations |
+--------+-----------------+
| Joomla | 2               |
| Drupal | 3               |
+--------+-----------------+

Version specific stats:
Joomla:
+---------+-----------------+
| Version | # Installations |
+---------+-----------------+
| 3.6.5   | 2               |
+---------+-----------------+
Drupal:
+---------+-----------------+
| Version | # Installations |
+---------+-----------------+
| Unknown | 1               |
| 8.2.7   | 2               |
+---------+-----------------+
```

**Comment by SniperSister** [comment]
Perfect, thanks!

**Comment by zero-24** [comment]
Thanks for the feedback 👍

**Pull request merged**
