### PR TITLE
Added PhpStorm .idea folder to gitignore

### PR DESCRIPTION
**Pull request by yvesh**

### CODE REVIEW

**Comment by astridx** [comment]
OK, File for PHPStorm

**Comment by zero-24** [comment]
Please also add `.vscode` ;)

**Comment by tobiasbaehr** [comment]
I believe the cleaner way is to use a whitelist. Means ignore all files and just add the directories/files which should added to git.

Example:
```
*
!/.gitignore
!src/
!src/**
!bin/
!bin/**
...
```

**Comment by yvesh** [comment]
Not a fan of whitelisting :-) But ¯\_(ツ)_/¯

@SniperSister opinions?

**Comment by SniperSister** [comment]
Not a whitelisting fan either, let's go with blacklisting

**Pull request merged**
